name: Test Mongo
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Mongo
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ["4.0", "4.2"] 
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Launch MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: ${{ matrix.mongodb-version }}